### ISSUE TITLE
Sort via drag & drop

### ISSUE THREAD

**Issue by jonasfeige** [sylvainjule/kirby-pagetable#23]
Any chance of being able to sort the pages via drag & drop as in the normal Kirby pages section?

Thanks for this great plugin, comes in very handy for a site I am working on right now.

**Comment by sylvainjule** [comment]
Probably not in the near future, no.

I actually intended this section to deal with a large number of pages, large enough to make manual sorting too tedious and therefore sorted automatically (by title, date, etc). 

I need to think about it because as the table is intended to be sortable, changing an item's order if this order has been changed can become a big mess. If I have the ability to sort them only when the default sorting is applied, it might also become confusing for the user.

For now you can sort them within the page options / clicking on the status dot, and I think I'll keep it that way, unless you have some ideas about how to handle the issues above?

**Comment by jonasfeige** [comment]
Yes, you’re right, changing the order via the status dot works fine, I was just wondering if drag & drop could be a little more convenient, but it’s definitely not necessary. And I agree, the complications between sorting on the frontend and updating the order and the backend can become very messy.
Is there any way to display the page’s order number in a column? Again, more of a convenience feature but I think it could be nice to be able to see the order number without clicking the status dot, especially when you are in a filtered view.

**Comment by nilshoerrmann** [comment]
What about having an additional column displaying the sort number, allowing drag and drop if the table is sorted by that column?

**Comment by sylvainjule** [comment]
Yes, that'd work !

**Comment by macx** [comment]
@sylvainjule Could you please bring that one back to attention?

**Comment by sylvainjule** [comment]
It never went far from attention, but this needs time that I haven't found yet :)
