### ISSUE TITLE
Limit option not working?

### ISSUE THREAD

**Issue by lareusmedia** [sylvainjule/kirby-pagetable#52]
Can anybody confirm that the limit option is currently not working?

I'm trying `limit: 50` but the list still shows only 10 items per page (and yes, there are more than 10 items)

**Comment by mattwolff** [comment]
Same problem for me. 

Trying to specify `limit: 25` or `limit: 50` the list will only show the default 10 items. Updating `limitOptions` worked as expected and I can add / toggle between numbers. Just can't set the default...

**Comment by mattwolff** [comment]
This morning I removed the plugin from my repo and then reinstalled it from composer. The `limit` options is working as expected... Could this have been something like caching issue?

**Comment by mattwolff** [comment]
Apologies for spamming this thread. I think I've got a better idea of what's going on now... Here are steps to reproduce the issue:

1. In your blueprint, define a `limit` for the pagetable. For instance `limit: 50` (This works as expected.)
2. Sort or Filter the table. 
3. Hit Reset 

After hitting 'Reset' the default `limit` is set back to `10` rather than whatever was defined in the blueprint. The limit will remain at 10 until starting a new session (new tab, window, etc.)

**Comment by bnomei** [comment]
@sylvainjule for me the limit is not working as well.
