### ISSUE TITLE
[Feature request] Support file sections

### ISSUE THREAD

**Issue by igregson** [sylvainjule/kirby-pagetable#58]
File sections would benefit from search, a per-page select, and sorting by column. Any reason this doesn't yet support file sections?

**Comment by sylvainjule** [comment]
I agree this could be useful, but it would then be an entire different plugin or a massive update I won't have time to maintain, because dealing with files and pages are two quite different things in Kirby. I haven't had the use case for this and therefore won't engage in this.

One could build this section with the help of [tbl-for-kirby](https://github.com/distantnative/tbl-for-kirby) like this plugin does.
